Controllers/GryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class GryController : Controller
    {
        private GameDBCtxt db = new GameDBCtxt();

        public ActionResult Wszystkie()
        {
            var games = db.Games;
            ViewBag.GamList = games.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Szukaj(string Find)
        {
            var games = from i in db.Games
                        select i;
            if (!String.IsNullOrEmpty(Find))
            {
                games = from i in db.Games
                        where i.FullName.Contains(Find)
                        select i;
            }
            ViewBag.GamList = games.ToList();
            return View();
        }

        public ActionResult Pobierz(int id = 0)
        {
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            game.Popularity++;
            List<String> LinkList = new List<String>();
            LinkList.Add("http://dos.16mb.com/?gra=" + game.Name);
            LinkList.Add("http://asnet.cba.pl/?gra=" + game.Name);
            LinkList.Add(game.Link);
            db.SaveChanges();

            ViewBag.GamLink = LinkList;
            return View(game);
        }



        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/KategorieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class KategorieController : Controller
    {

        private GameDBCtxt db = new GameDBCtxt();
        public ActionResult Wszystkie()
        {
            List<Game>[] top5Games = new List<Game>[20];
            var groupedGames = db.Games
                .GroupBy(s => s.CategoryID)
                .Select(g => g.Take(5));

            groupedGames.ToList().ForEach(s =>
            {
                top5Games[s.First().CategoryID] = s.ToList();
            });

            ViewData["Cats"] = db.Categories
                .OrderBy(s => s.CategoryPL)
                .ToList();

            ViewData["ViewCatGam"] = top5Games;
            return View();
        }

        public ActionResult Kategoria(int id = 0)
        {
            Category CatList = db.Categories.Find(id); ;
            ViewData["Cat"] = CatList;
            var CatGam = from i in db.Games
                         where i.CategoryID.Equals(id)
                         select i;
            ViewData["ViewCatGam"] = CatGam;
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Kategorie/Kategoria.cshtml
@model IEnumerable<MvcApplication1.Models.Game>
@{
    ViewBag.Title = "Kategoria " + ViewBag.Cat.CategoryPL;
}

<h2>@ViewBag.Cat.CategoryPL</h2>
<br>
<div class="gamList">
    @foreach (var item in ViewBag.ViewCatGam)
    {
        <div onclick="location.href='@Url.Action("Pobierz", "Gry", new { id = item.Id })'">
            <img style="height: 160px; width: 160px;" src="../Images/@item.Image" /><br>
            <b>@item.FullName</b>
            <br>
            <span class="star-rating">
                <i style="width: 90%;"></i>
            </span>
            <br>
            Rozmiar: @item.Size MB
        </div>
    }
</div>

Views/Kategorie/Wszystkie.cshtml
@model IEnumerable<MvcApplication1.Models.Game>
@{
    ViewBag.Title = "Kategorie";
}
<h2>Kategorie</h2>
<br>

@foreach (var itemArray in ViewBag.Cats)
{
    <table>
        <tr>
            <td>
                <div class="content-wrapper">
                    <div class="float-left">
                        <h2 onclick="location.href='@Url.Action("Kategoria", "Kategorie", new { id = itemArray.CategoryID })'">@itemArray.CategoryPL</h2>
                    </div>
                    <div class="float-right">
                        <section id="cats">
                            <a href="@Url.Action("Kategoria", "Kategorie", new { id = itemArray.CategoryID })">Pokaż wszystkie</a>
                        </section>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="gamList">
                    @foreach (var item in ViewBag.ViewCatGam[itemArray.CategoryID])
                    {
                        <div onclick="location.href='@Url.Action("Pobierz", "Gry", new { id = item.Id })'">
                            <img style="height: 160px; width: 160px;" src="../Images/@item.Image" /><br>
                            <b>@item.FullName</b>
                            <br>
                            <span class="star-rating">
                                <i style="width: 90%;"></i>
                            </span>
                            <br>
                            Rozmiar: @item.Size MB
                        </div>
                    }
                </div>
            </td>
        </tr>
    </table>
}